### PR TITLE
Replace trove with fastutil HashMap

### PR DESCRIPTION
**Pull request by timlueg**
When opening the plugin in CLion 2024.2 I encountered this `NoClassDefFoundError`:

<details>
  <summary>java.lang.ClassNotFoundException: org.jetbrains.coverage.gnu.trove.TObjectHashingStrategy</summary>

    ```
    java.lang.NoClassDefFoundError: org/jetbrains/coverage/gnu/trove/TObjectHashingStrategy
	at com.lasagnerd.odin.lang.OdinParser.procedureDefinition(OdinParser.java:2667)
	at com.lasagnerd.odin.lang.OdinParser.procedureDeclarationStatement(OdinParser.java:2627)
	at com.lasagnerd.odin.lang.OdinParser.fileScopeStatement(OdinParser.java:1620)
	at com.lasagnerd.odin.lang.OdinParser.fileScopeStatementList_0(OdinParser.java:1652)
	at com.lasagnerd.odin.lang.OdinParser.fileScopeStatementList(OdinParser.java:1640)
	at com.lasagnerd.odin.lang.OdinParser.fileScope(OdinParser.java:1581)
	at com.lasagnerd.odin.lang.OdinParser.odinFile(OdinParser.java:2414)
	at com.lasagnerd.odin.lang.OdinParser.parse_root_(OdinParser.java:36)
	at com.lasagnerd.odin.lang.OdinParser.parse_root_(OdinParser.java:32)
	at com.lasagnerd.odin.lang.OdinParser.parseLight(OdinParser.java:27)
	at com.lasagnerd.odin.lang.OdinParser.parse(OdinParser.java:19)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:60)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:38)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:183)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:535)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:182)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:234)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:121)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:33)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:233)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:206)
	at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.findFirstBreadcrumbedElement(PsiFileBreadcrumbsCollector.java:217)
	at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.findStartElement(PsiFileBreadcrumbsCollector.java:175)
	at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.computePsiElements(PsiFileBreadcrumbsCollector.java:109)
	at com.intellij.openapi.editor.impl.stickyLines.StickyLinesCollector.collectLines(StickyLinesCollector.kt:96)
	at com.intellij.codeInsight.stickyLines.StickyLinesPass.doCollectInformation(StickyLinesPass.kt:23)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.coverage.gnu.trove.TObjectHashingStrategy PluginClassLoader(plugin=PluginDescriptor(name=Odin Support, id=com.lasagnerd.odin, descriptorPath=plugin.xml, path=~/Projects/misc/odin-intellij/build/idea-sandbox/CL-2024.2/plugins/odin-intellij, version=0.5.2, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/.gradle/caches/8.9/transforms/dc2d49e1578ebbb82de46674ed8db11d/transformed/CLion-2024.2/lib, version=242.20224.384, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/.gradle/caches/8.9/transforms/dc2d49e1578ebbb82de46674ed8db11d/transformed/CLion-2024.2/lib, version=242.20224.384, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/.gradle/caches/8.9/transforms/dc2d49e1578ebbb82de46674ed8db11d/transformed/CLion-2024.2/lib, version=242.20224.384, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/.gradle/caches/8.9/transforms/dc2d49e1578ebbb82de46674ed8db11d/transformed/CLion-2024.2/lib, version=242.20224.384, package=null, isBundled=true), PluginDescriptor(name=Native Debugging Support, id=com.intellij.nativeDebug, descriptorPath=plugin.xml, path=~/.gradle/caches/8.9/transforms/dc2d49e1578ebbb82de46674ed8db11d/transformed/CLion-2024.2/plugins/nativeDebug-plugin, version=242.20224.384, package=null, isBundled=true), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 53 more

    ```

</details>

Seems like trove4j is obsolete. Replacing `TObjectIntHashMap` with fastutil `Object2IntOpenHashMap` seems to work. (But not sure if this is the most optimal alternative.)

### CODE REVIEW

**Comment by timlueg** [comment]
There seems to be a lexer issue introduced with this change.

**Comment by obiwan87** [comment]
So the plugin is not usable in CLion?

**Comment by obiwan87** [comment]
I accepted the pull request and fill any subsequent issues. Thank you :)

**Comment by obiwan87** [comment]
Release 0.5.3 with your fix.

**Comment by timlueg** [comment]
But it seems the parsing does not work correctly with my changes. That is why filescope is null when encountering core.odin. (The patch you just made)

I narrowed it down to this small examples that it cant parse/lex.

```

package main

test :: proc () {
for {}
}

TestStruct :: struct {
test1: i32
}

test2 :: proc() -> TestStruct {
return TestStruct{1}
}

main :: proc() {

}
```

**Comment by obiwan87** [comment]
That shouldn't have anything to do with the map. I think it has to do with the cached files of the SDK. Try invalidating the caches and restarting the IDE

**Comment by obiwan87** [comment]
Ok, turns out changing the map actually revealed two bugs that were cancelling each other out with the other map. 🧐

**Comment by timlueg** [comment]
With you latest changes it works now in CLion!

Consider reverting https://github.com/obiwan87/odin-intellij/commit/a5b3a4668dd9873c414cf93018052fb335388180 . It's probably good to get the Exception when these odin files are incorrectly parsed ?
(I only noticed the issue because of it.)

I'm Curious to know how you approach(ed) debugging .flex / .bnf issues.

**Comment by obiwan87** [comment]
Debugging those is painful. Basically, finding the minimal code that fails (which you provided), lots of staring at the screen and console debugging .

**Comment by obiwan87** [comment]
There is class called OdinParserUtil, which contains all custom parsing rules. Basically, when you enter certain statements, some expressions are not allowed, because they would lead to ambiguous code. Example:

```
for MyStruct{ } {
}
```

in the example above, initizalizing a struct in the condition statement of an for-block (and a for ... in block) is not allowed, as it is impossible to tell whether the `MyStruct` should be evaluated as a simple boolean expression followed by the for-statement block, or if it is a struct literal `MyStruct {}` followed by the for-statement block. This means, that when you enter an for-block you set the parsing state to a "NO_BLOCK"-mode, which disallows expressions such as struct-literals.
At the end of the condition block, the "NO_BLOCK"-mode is exited. 

However, if the rule doesn't match until the "NO_BLOCK"-mode is exited, then the parser will wrongly stay in the "NO_BLOCK"-mode. 
In this case it happened because the parser always first evaluates  the "for... in" rule and only after that it will check for a "for"-statement witout in. This means that the parser, only partially matched the "for...in" rule , leaving the parsing in a wrong state. In your example, that happens inside the `test`procedure.  

The fix was to add a predicate rule to the for-in blockm which eagerly evaluates the "... in ..." part of the "for-in" rule and only after that enters the block mode. This makes sure, that the entering and exiting of the NO_BLOCK mode is either not executed or executed completely.

**Pull request merged**
