### PR TITLE
WIP: Using 'odin build' to display errors and warnings

### PR DESCRIPTION
**Pull request by Dima-369**
There were many issues coming up when adding my code, I am still fixing them, but feel free to check them out as well. My code worked in `master` apparently.

Issues:

1. `odin build` is never run. Is there an issue with `canRunOdinBuild()`?

2. Is this an issue? The files exist:

CleanShot 2024-08-13 at 13 49 30@2x

3. `OdinSdkFilesIndexContributor.java` crashed, so I added `try/catch` on indexing some files, maybe the same issue as in 2.?

### CODE REVIEW

**Comment by Dima-369** [comment]
@obiwan87 would you like to try to fix the issues yourself? The new IntelliJ version behaves differently apparently.

**Comment by obiwan87** [comment]
Thank you for reporting the issues. The OdinFileIndexContributor issue is known to me. The other ones might just be a consequence of files not yet being indexed. 
Yes, I'll fix it myself. Thank you! :)

**Comment by Dima-369** [comment]
> Were you able to build the plugin using 2024.2?

Yeah, it works.

> Does your code add any additional issues?

Nothing apart what I noted above. I am just a bit sad that the error reporting doesn't work on 2024.2, and I haven't figured out why 😢

**Comment by obiwan87** [comment]
It does work! But if there's other errors in the file - such as the ones produced by my annotator -  your annotator will just returns.

**Comment by Dima-369** [comment]
> It does work! But if there's other errors in the file - such as the ones produced by my annotator - your annotator will just return.

Oh yeah, I see!

**Comment by obiwan87** [comment]
Anyway, I just fixed some issues with Windows (like the missing ".exe" in the end. Will commit and push in a sec

**Comment by Dima-369** [comment]
I also left in many calls to `Notifier.notify(...` while debugging this PR, those were merged - let's remove/comment them out.

**Comment by obiwan87** [comment]
> > Also, you can use odin check 'path to dir or file' --json-errors which should be faster
> 
> Oh yeah, I was looking for this the whole time. Cool!
> 
> It works the same from what I see, can you switch to it?

Yes, I will switch to it. It might even make the "Directory to compile" obsolete, as you can indicate a single file.

**Comment by obiwan87** [comment]
Ok, just pushed. Can you please test if it works for you on mac?

**Pull request merged**
